# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-11 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20191010_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='cname',
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(db_column='cname', on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ForeignKey(db_column='location', on_delete=django.db.models.deletion.CASCADE, to='news.Location'),
        ),
    ]
